### ISSUE TITLE
[ISSUE] [VISTAS] - Falta de mensaje de bienvenida intuitiva en el Panel Administrador al iniciar sesión

### ISSUE THREAD

**Issue by Mckendo2** [SMUK0/Proyecto3LEVIATAN#14]
Al iniciar sesión en el Panel Administrador, no se muestra un mensaje de bienvenida. Esto puede generar confusión en el usuario, ya que no recibe ninguna indicación visual de que ha ingresado correctamente al sistema.

![Captura de pantalla 2024-11-06 171419](https://github.com/user-attachments/assets/695c8134-0202-4c79-a20a-82be389626f3)

**Comment by SMUK0** [comment]
Ya se arreglo, funciona como deberia.
