### ISSUE TITLE
[BUG][ADMINISTRADOR]Validación faltante en el campo de nombre de Materia

### ISSUE THREAD

**Issue by Mckendo2** [SMUK0/Proyecto3LEVIATAN#17]
En el módulo de CRUD de materias, al agregar una nueva materia, el campo de "Nombre" permite ingresar números. Esto puede causar inconsistencias, ya que los nombres de las materias generalmente deberían ser textos descriptivos (alfabéticos) y no numéricos.

![image](https://github.com/user-attachments/assets/1304dd70-f353-4355-adaf-a92d5bb94731)

**Comment by SMUK0** [comment]
Ya se arreglo, funciona como deberia.
