### ISSUE TITLE
[INCIDENTE] [CURSO-ESTUDIANTE] -Al borrar el curso se borra el estudiante

### ISSUE THREAD

**Issue by SMUK0** [SMUK0/Proyecto3LEVIATAN#25]
![{40E4B420-6FC6-4AB4-9D36-A1BE5FA4C4D4}](https://github.com/user-attachments/assets/794e9007-f95e-4506-a545-8a0f707e04eb)
![{E02F45A3-3C04-4ABE-8F08-C8FE150DB5A6}](https://github.com/user-attachments/assets/eff4be8e-1e52-4436-8171-03f2e503a707)

**Comment by SMUK0** [comment]
Talvez es error de la BD

**Comment by CesarLopez66** [comment]
El [INCIDENT] fue solucionado y ya no ocurre la eliminacion de los estudiantes relacionados al curso eliminado.
