### ISSUE TITLE
[ERROR] [VISTAS] - No permite ejecutar mas de una sesion a la vez.

### ISSUE THREAD

**Issue by CesarLopez66** [SMUK0/Proyecto3LEVIATAN#27]
El sistema no permite ejecutar mas de una sesión a la vez.
Al momento de tener una sesion iniciada y tratar de abrir otra sea en el mismo dispositivo o uno diferente salta error de credenciales.

**Comment by SMUK0** [comment]
Ya se arreglo, funciona como deberia.
